--- 
title: 'Topics in Quantum Information Science'
author: 'Ali ALMASI'
date: '`r Sys.Date()`'
site: bookdown::bookdown_site
output: bookdown::bs4_book
documentclass: krantz
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
bibliography:
  - geocompr.bib
  - packages.bib
biblio-style: apalike
link-citations: yes
colorlinks: yes
graphics: yes
description: "Geocomputation with R is for people who want to analyze, visualize and model geographic data with open source software. It is based on R, a statistical programming language that has powerful data processing, visualization, and geospatial capabilities. The book equips you with the knowledge and skills to tackle a wide range of issues manifested in geographic data, including those with scientific, societal, and environmental implications. This book will interest people from many backgrounds, especially Geographic Information Systems (GIS) users interested in applying their domain-specific knowledge in a powerful open source language for data science, and R users interested in extending their skills to handle spatial data."
github-repo: "geocompx/geocompr"
url: https://github.com/ali-almasi/qis
---

# About {-}
*Topics in Quantum Information Science* is an introduction to the fascinating and rapidly growing field of quantum information science. It is written for those with a background in mathematics or theoretical computer science who are curious about exploring this field through mathematical and computational lenses.

These notes do not aim to cover everything—quantum information science has grown far too vast for that. Instead, they offer a selection of topics that I have found particularly interesting in my own journey of learning.

Unless stated otherwise, the results presented here are not original, and citations are provided wherever possible.


<!--chapter:end:index.Rmd-->

# (PART) QInformation Theory {-}
# The pool of tears

$$
a^2 + \mathbf{b}^2 = \symbf{\alpha}^2\,.  
$$
# Tips on writing mathematics  {.unnumbered #writing}

::: {.mysummary}
In the mid-semester survey, a few people suggested I could offer some clearer advice on writing mathematics well. This is a brief attempt at doing that. I may try to expand this a bit later.
:::

## Advice {.unnumbered #advice}

If a maths question asks you to "State", "Write down" or "Calculate" something, you don't need to do any more than give the answer. But if a question asks you to "Prove", "Show that" or "Explain", then the marker is looking for a clearly explained answer, and will base your mark on how well you explain your solution, not just on it's mathematical accuracy.

Some things a marker might look for include:

* If you had to make your own notation, have you explained clearly what it means?
* If it's a "words question", have you clearly translated the information into mathematical notation?
* In your solution, do you clearly state how you know certain statements are true? ("From the question, we know that..." "From the definition of ..." "Using the law of total probability..." "From Axiom 2, we see that...")
* When making non-obvious algebraic manipulations, do you explain what you're doing? (There's usually no need -- but no harm either! -- in stating obvious things like "Dividing both sides by 2...", but for less obvious things like "Recognising this as difference of two squares..." or "By the linearity of expectation...", you should say so.)
* Does your solution show clearly the "direction" of the proof. ("We start with the definition of..." "We need to show that..." "Assume, seeking a contradiction, that..." "If we could show that ... then this would be sufficient to give the result." "We will bound each term in this expression separately.")
* Do you write in full sentences? Even equations should (usually) include punctuation, such as ending with a full-stop if they end a sentence.
* An extremely rough rule of thumb -- which is often, but not always, applicable -- is that a good solution should be at least 50% writing and at most 50% equations.
* It's usually best to avoid abbreviations and shorthand, like "LHS" ("left-hand side"), "WLOG" ("without loss of generality"), "iff" ("if and only if"), etc, although specific technical abbreviations from the course, like "PMF" ("probability mass function") are OK. Mathematical shorthand like $\therefore$ or $\Rightarrow$ should be avoided as "word alternatives" ("So", "Thus", "Therefore", "Hence", etc, are better), but are OK in certain circumstances where they have specific technical meanings.
* It's fine -- and often good! -- to use diagrams to aid your explanation. But a diagram is rarely sufficient by itself without some writing to explain what it shows.

## Examples  {.unnumbered #writing-ex}

Here are two solutions for [Problem Sheet 3 Question B1](#P3-long). This first solution is a typical sort of solution I might see from a student. The second solution has exactly the same mathematical content, but is more clearly explained. Which do you think is better?

::: {.thpart}
**Problem Sheet 3, Question B1.** *Suppose $A$ and $B$ are independent events. Show that $A$ and $B^\comp$ are also independent events.*
:::

::: {.thpart}
*Solution 1.* 



<!--chapter:end:01-QInfo1.Rmd-->

# (PART) QAlgorithms {-}

# The pool of tears

<!--chapter:end:10-QAlgo1.Rmd-->

# (PART) ZX Calculus {-}

# The pool of tears
df


<!--chapter:end:20-ZXCalculus1.Rmd-->

